name: Add Repo Variables

on:
  workflow_dispatch:

jobs:
  add-repo-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Repository Variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define all variables
          declare -A variables=(
              ["AZURE_CLIENT_ID"]="test"
              ["AZURE_TENANT_ID"]="test"
              ["AZURE_SUBSCRIPTION_ID"]="test"
              ["AZURE_ENV_NAME"]="test"
              ["AZURE_LOCATION"]="test"
              ["AZURE_OPENAI_SERVICE"]="test"
              ["AZURE_OPENAI_API_VERSION"]="test"
              ["AZURE_OPENAI_RESOURCE_GROUP"]="test"
              ["AZURE_COMPUTER_VISION_SERVICE"]="test"
              ["AZURE_COMPUTER_VISION_RESOURCE_GROUP"]="test"
              ["AZURE_COMPUTER_VISION_LOCATION"]="test"
              ["AZURE_COMPUTER_VISION_SKU"]="test"
              ["AZURE_FORMRECOGNIZER_SERVICE"]="test"
              ["AZURE_FORMRECOGNIZER_RESOURCE_GROUP"]="test"
              ["AZURE_FORMRECOGNIZER_SKU"]="test"
              ["AZURE_SEARCH_INDEX"]="test"
              ["AZURE_SEARCH_SERVICE"]="test"
              ["AZURE_SEARCH_SERVICE_RESOURCE_GROUP"]="test"
              ["AZURE_SEARCH_SERVICE_LOCATION"]="test"
              ["AZURE_SEARCH_SERVICE_SKU"]="test"
              ["AZURE_SEARCH_QUERY_LANGUAGE"]="test"
              ["AZURE_SEARCH_QUERY_SPELLER"]="test"
              ["AZURE_SEARCH_SEMANTIC_RANKER"]="test"
              ["AZURE_STORAGE_ACCOUNT"]="test"
              ["AZURE_STORAGE_RESOURCE_GROUP"]="test"
              ["AZURE_STORAGE_SKU"]="test"
              ["AZURE_APP_SERVICE_PLAN"]="test"
              ["AZURE_APP_SERVICE_SKU"]="test"
              ["AZURE_APP_SERVICE"]="test"
              ["AZURE_OPENAI_CHATGPT_MODEL"]="test"
              ["AZURE_OPENAI_CHATGPT_DEPLOYMENT"]="test"
              ["AZURE_OPENAI_CHATGPT_DEPLOYMENT_CAPACITY"]="test"
              ["AZURE_OPENAI_CHATGPT_DEPLOYMENT_VERSION"]="test"
              ["AZURE_OPENAI_EMB_MODEL_NAME"]="test"
              ["AZURE_OPENAI_EMB_DEPLOYMENT"]="test"
              ["AZURE_OPENAI_EMB_DEPLOYMENT_CAPACITY"]="test"
              ["AZURE_OPENAI_EMB_DEPLOYMENT_VERSION"]="test"
              ["AZURE_OPENAI_EMB_DIMENSIONS"]="test"
              ["OPENAI_HOST"]="test"
              ["OPENAI_API_KEY"]="test"
              ["OPENAI_ORGANIZATION"]="test"
              ["AZURE_USE_APPLICATION_INSIGHTS"]="test"
              ["AZURE_APPLICATION_INSIGHTS"]="test"
              ["AZURE_APPLICATION_INSIGHTS_DASHBOARD"]="test"
              ["AZURE_LOG_ANALYTICS"]="test"
              ["USE_VECTORS"]="test"
              ["USE_GPT4V"]="test"
              ["AZURE_VISION_ENDPOINT"]="test"
              ["VISION_SECRET_NAME"]="test"
              ["USE_SPEECH_INPUT_BROWSER"]="test"
              ["USE_SPEECH_OUTPUT_BROWSER"]="test"
              ["USE_SPEECH_OUTPUT_AZURE"]="test"
              ["AZURE_SPEECH_SERVICE"]="test"
              ["AZURE_SPEECH_SERVICE_RESOURCE_GROUP"]="test"
              ["AZURE_SPEECH_SERVICE_LOCATION"]="test"
              ["AZURE_SPEECH_SERVICE_SKU"]="test"
              ["AZURE_KEY_VAULT_NAME"]="test"
              ["AZURE_USE_AUTHENTICATION"]="test"
              ["AZURE_ENFORCE_ACCESS_CONTROL"]="test"
              ["AZURE_ENABLE_GLOBAL_DOCUMENT_ACCESS"]="test"
              ["AZURE_ENABLE_UNAUTHENTICATED_ACCESS"]="test"
              ["AZURE_AUTH_TENANT_ID"]="test"
              ["AZURE_SERVER_APP_ID"]="test"
              ["AZURE_CLIENT_APP_ID"]="test"
              ["ALLOWED_ORIGIN"]="test"
              ["AZURE_ADLS_GEN2_STORAGE_ACCOUNT"]="test"
              ["AZURE_ADLS_GEN2_FILESYSTEM_PATH"]="test"
              ["AZURE_ADLS_GEN2_FILESYSTEM"]="test"
          )

          # Set GitHub repository variables
          for key in "${!variables[@]}"; do
            gh variable set $key --body "${variables[$key]}"
          done
