name: Add Repo Variables

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  id-token: write

jobs:
  add-repo-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Repository Variables
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Define all variables with non-empty values
          declare -A variables=(
              ["AZURE_CLIENT_ID"]="cc435f05-a449-4cb9-a3ee-fc4187ffd1ae"
              ["AZURE_TENANT_ID"]="4720ed5e-c545-46eb-99a5-958dd333e9f2"
              ["AZURE_SUBSCRIPTION_ID"]="91f14ce4-f7e5-497f-9d8f-43cbf0255733"
              ["AZURE_ENV_NAME"]="cicd"
              ["AZURE_LOCATION"]="centralus"
              ["AZURE_OPENAI_SERVICE"]="cog-dr6tfi6eucgcx"
              ["AZURE_OPENAI_RESOURCE_GROUP"]="rg-cicd"
              ["AZURE_FORMRECOGNIZER_SERVICE"]="cog-fr-dr6tfi6eucgcx"
              ["AZURE_FORMRECOGNIZER_RESOURCE_GROUP"]="rg-cicd"
              ["AZURE_SEARCH_INDEX"]="gptkbindex"
              ["AZURE_SEARCH_SERVICE"]="gptkb-dr6tfi6eucgcx"
              ["AZURE_SEARCH_SERVICE_RESOURCE_GROUP"]="rg-cicd"
              ["AZURE_SEARCH_SEMANTIC_RANKER"]="free"
              ["AZURE_STORAGE_ACCOUNT"]="stdr6tfi6eucgcu"
              ["AZURE_STORAGE_RESOURCE_GROUP"]="rg-cicd"
              ["AZURE_OPENAI_CHATGPT_MODEL"]="gpt-35-turbo"
              ["AZURE_OPENAI_CHATGPT_DEPLOYMENT"]="chat"
              ["AZURE_OPENAI_EMB_MODEL_NAME"]="text-embedding-ada-002"
              ["AZURE_OPENAI_EMB_DEPLOYMENT"]="embedding"
              ["OPENAI_HOST"]="azure"
              ["AZURE_USE_AUTHENTICATION"]="false"
          )

          # Set GitHub repository variables
          for key in "${!variables[@]}"; do
            gh variable set $key --body "${variables[$key]}"
          done
